export const ACTIONS_ASSETS_NFTS = {
    _INITIAL_: 'INITIAL',
    _SUCCESS_GET_ASSETS_: 'SUCCESS_GET_ASSETS',
    _FAILURE_GET_ASSETS_: 'FAILURE_GET_ASSETS',
    _SET_LIMIT_PAGE_: 'SET_LIMIT_PAGE',
    _SET_ORDER_DIRECTION_: 'SET_ORDER_DIRECTION',
    _SET_INCLUDE_ORDERS_: 'SET_INCLUDE_ORDERS',
    // ~ se setean en el success
    // _SET_ADDRESS_NEW_PAGE_: 'SET_ADDRESS_NEW_PAGE',
    // _SET_ADDRESS_OLD_PAGE_: 'SET_ADDRESS_OLD_PAGE',
}
    ;

