export const ACTIONS_COLLECTION_NFTS = {
    _INITIAL_SEARCH_COLLECTION_: "_INITIAL_SEARCH_COLLECTION_",
    // _success_GET_COLLECTION_: "_success_GET_COLLECTION_",
    _SUCCESS_SEARCH_COLLECTION_: "_SUCCESS_SEARCH_COLLECTION_",
    _FAILURE_GET_COLLECTION_: "_FAILURE_GET_COLLECTION_",
}