// actions to reducer opensea.reducer.js:
export const _SET_DATA_OPEN_SEA = '_SET_DATA_OPEN_SEA';
export const _SET_ERR_OPEN_SEA = '_SET_ERR_OPEN_SEA';
export const _SET_LOADING_OPEN_SEA = '_SET_LOADING_OPEN_SEA';
export const _SET_LIMIT_OPEN_SEA = '_SET_LIMIT_OPEN_SEA';
export const _SET_OFFSET_OPEN_SEA = '_SET_OFFSET_OPEN_SEA';



export const OPEN_SEA_ACIONS = {
    _INITIAL_SEARCH_OPEN_SEA: '_SET_INTIAAL_SEARCH_OPEN_SEA',
    _SUCCESS_SEARCH_OPEN_SEA: '_SUCESS_SEARCH_OPEN_SEA',
    _ERROR_SEARCH_OPEN_SEA: '_ERROR_SEARCH_OPEN_SEA',
    _SET_LIMIT_OPEN_SEA: '_SET_LIMIT_OPEN_SEA',
    _SET_OFFSET_OPEN_SEA: '_SET_OFFSET_OPEN_SEA',

}