export const _SET_DATA_OPEN_SEA = '_SET_DATA_OPEN_SEA';
export const _SET_ERR_OPEN_SEA = '_SET_ERR_OPEN_SEA';
export const _SET_LOADING_OPEN_SEA = '_SET_LOADING_OPEN_SEA';
export const _SET_LIMIT_OPEN_SEA = '_SET_LIMIT_OPEN_SEA';
export const _SET_OFFSET_OPEN_SEA = '_SET_OFFSET_OPEN_SEA';
